using GridForge.Grids;
using SwiftCollections;
using System;
using System.Runtime.CompilerServices;

namespace GridForge.Spatial;

/// <summary>
/// Represents the world-scoped runtime identity of a voxel.
/// Used for uniquely identifying voxels across multiple grids and world instances.
/// </summary>
public struct WorldVoxelIndex : IEquatable<WorldVoxelIndex>
{
    #region Properties

    /// <summary>
    /// The runtime token of the owning <see cref="GridWorld"/> instance.
    /// Used to reject stale or cross-world identities safely.
    /// </summary>
    public int WorldSpawnToken;

    /// <summary>
    /// The world-local slot index of the grid in <see cref="GridWorld.ActiveGrids"/>.
    /// </summary>
    public ushort GridIndex;

    /// <summary>
    /// The unique identifier generated by the grid during initialization.
    /// Used to ensure the correct instance is at the assigned <see cref="GridIndex"/>.
    /// </summary>
    public int GridSpawnToken;

    /// <summary>
    /// The local coordinate of a voxel within the grid at <see cref="GridIndex"/>.
    /// </summary>
    public VoxelIndex VoxelIndex;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of <see cref="WorldVoxelIndex"/>, linking a voxel to a specific world and grid instance.
    /// </summary>
    public WorldVoxelIndex(
        int worldSpawnToken,
        ushort gridIndex,
        int gridSpawnToken,
        VoxelIndex coord)
    {
        WorldSpawnToken = worldSpawnToken;
        GridIndex = gridIndex;
        GridSpawnToken = gridSpawnToken;
        VoxelIndex = coord;
    }

    #endregion

    #region operators

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(WorldVoxelIndex left, WorldVoxelIndex right)
    {
        return left.Equals(right);
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(WorldVoxelIndex left, WorldVoxelIndex right)
    {
        return !(left == right);
    }

    #endregion

    #region Overrides

    /// <summary>
    /// Returns a string representation of the world-scoped voxel identity.
    /// </summary>
    public override readonly string ToString()
    {
        return $"World: {WorldSpawnToken}; Grid: {GridIndex}; Coordinate: {VoxelIndex}";
    }

    /// <summary>
    /// Computes a hash code for uniquely identifying this world-scoped voxel identity.
    /// </summary>
    public override readonly int GetHashCode() =>
        SwiftHashTools.CombineHashCodes(WorldSpawnToken, GridSpawnToken, GridIndex, VoxelIndex);

    /// <inheritdoc/>
    public readonly bool Equals(WorldVoxelIndex other)
    {
        return WorldSpawnToken == other.WorldSpawnToken
            && GridIndex == other.GridIndex
            && GridSpawnToken == other.GridSpawnToken
            && VoxelIndex.Equals(other.VoxelIndex);
    }

    /// <inheritdoc/>
    public override readonly bool Equals(object? obj) => obj is WorldVoxelIndex other && Equals(other);

    #endregion
}
